export interface PluginSettings {
  enabled: boolean;
  whitelistAuthors: string[];
  whitelistDomains: string[];
  sensitivityThreshold: number;
  blockedPhrases: string[];
  enableSpaMode: boolean;
  hideSlopCompletely: boolean;
  authorWhitelist: string[];
  debugMode: boolean;
  enableTelemetry: boolean;
  remoteRulesUrl: string;
  activeModules?: Record<string, boolean>;
}

export const DEFAULT_SETTINGS: PluginSettings = {
  enabled: true,
  whitelistAuthors: ['Gemini', 'ChatGPT', 'Claude'],
  whitelistDomains: [
    // LLM/AI
    'chatgpt.com',
    'openai.com',
    'claude.ai',
    'gemini.google.com',
    'deepseek.com',
    'perplexity.ai',
    'copilot.microsoft.com',

    // Banki i finanse PL
    'mbank.pl',
    'online.mbank.pl',
    'pkobp.pl',
    'ipko.pl',
    'iko.pkobp.pl',
    'pekao.com.pl',
    'pekao24.pl',
    'ing.pl',
    'mojeing.pl',
    'santander.pl',
    'aliorbank.pl',
    'alioronline.pl',
    'millenniumbank.pl',
    'bankmillennium.pl',
    'bnpparibas.pl',
    'goonline.bnpparibas.pl',
    'nestbank.pl',
    'credit-agricole.pl',
    'ca24.credit-agricole.pl',
    'velobank.pl',
    'bosbank.pl',
    'sgb.pl',
    'bps.pl',
    'bankpocztowy.pl',
    'pocztowy.pl',
    'citibank.pl',
    'citi.com',
    'handlowy.pl',
    'toyotabank.pl',
    'plusbank.pl',
    'banknowy.pl',
    'bfg.pl',
    'knf.gov.pl',

    // Płatności / fintech / bramki
    'blik.com',
    'payu.pl',
    'payu.com',
    'przelewy24.pl',
    'p24.pl',
    'tpay.com',
    'stripe.com',
    'paypal.com',
    'paypo.pl',
    'klarna.com',
    'klarna.pl',
    'revolut.com',
    'wise.com',
    'apple.com',
    'pay.google.com',
    'pay.google',
    'payments.google.com',

    // Administracja publiczna / e-usługi / identity
    'gov.pl',
    'www.gov.pl',
    'mobywatel.gov.pl',
    'epuap.gov.pl',
    'pacjent.gov.pl',
    'podatki.gov.pl',
    'biznes.gov.pl',
    'obywatel.gov.pl',
    'ceidg.gov.pl',
    'ekrs.ms.gov.pl',
    'prs.ms.gov.pl',
    'zus.pl',
    'pue.zus.pl',
    'nfz.gov.pl',
    'ue.gov.pl',
    'krus.gov.pl',
    'senat.gov.pl',
    'sejm.gov.pl',
    'prezydent.pl',
    'rp.pl',
    'policja.pl',
    'udt.gov.pl',
    'gum.gov.pl',
    'stat.gov.pl',
    'gus.gov.pl',
    'up.gov.pl',
    'eoz.mz.gov.pl',

    // Zdrowie / apteki / konta pacjenta
    'pacjent.gov.pl',
    'znanylekarz.pl',
    'doz.pl',
    'gemini.pl',
    'drmax.pl',
    'apteka-melissa.pl',
    'ktomalek.pl',

    // Poczta / email / skrzynki / komunikacja krytyczna
    'gmail.com',
    'mail.google.com',
    'outlook.com',
    'outlook.live.com',
    'office.com',
    'icloud.com',
    'mail.yahoo.com',
    'proton.me',
    'protonmail.com',
    'wp.pl',
    'o2.pl',
    'interia.pl',
    'onet.pl',

    // Komunikatory i współpraca
    'messenger.com',
    'web.whatsapp.com',
    'whatsapp.com',
    'slack.com',
    'discord.com',
    'teams.microsoft.com',
    'teams.live.com',
    'telegram.org',
    'web.telegram.org',
    'signal.org',
    'skype.com',
    'meet.google.com',
    'zoom.us',

    // Wyszukiwarki / konta / ekosystemy
    'google.com',
    'google.pl',
    'accounts.google.com',
    'myaccount.google.com',
    'drive.google.com',
    'docs.google.com',
    'mail.google.com',
    'microsoft.com',
    'account.microsoft.com',
    'office.com',
    'live.com',
    'apple.com',
    'account.apple.com',
    'icloud.com',

    // Marketplace / e-commerce PL
    'allegro.pl',
    'olx.pl',
    'amazon.pl',
    'amazon.com',
    'ceneo.pl',
    'empik.com',
    'empikfoto.pl',
    'erli.pl',
    'morele.net',
    'x-kom.pl',
    'euro.com.pl',
    'oleole.pl',
    'mediaexpert.pl',
    'mediamarkt.pl',
    'komputronik.pl',
    'neonet.pl',
    'rtvagd.sklep.pl',
    'sferis.pl',

    // Duże sklepy i retail
    'ikea.com',
    'ikea.com/pl',
    'castorama.pl',
    'leroymerlin.pl',
    'obi.pl',
    'jula.pl',
    'agatameble.pl',
    'blackredwhite.pl',
    'abra-meble.pl',
    'decathlon.pl',
    'zalando.pl',
    'eobuwie.com.pl',
    'ccc.eu',
    'reserved.com',
    'hm.com',
    'zara.com',
    'deichmann.com',
    'answear.com',
    'modivo.pl',
    'domodi.pl',
    'allani.pl',
    'nike.com',
    'adidas.pl',
    'rossmann.pl',
    'hebe.pl',
    'superpharm.pl',

    // Operatorzy i panele klienta
    'orange.pl',
    'play.pl',
    'plus.pl',
    't-mobile.pl',
    'nju.mobile.pl',
    'virginmobile.pl',
    'mobilevikings.pl',
    'vectra.pl',
    'upc.pl',
    'inea.pl',
    'netia.pl',
    'cyfrowypolsat.pl',
    'polsatbox.pl',
    'canalplus.com',
    'canalplus.pl',

    // Kurierzy / logistyka / śledzenie przesyłek
    'inpost.pl',
    'inpost.com',
    'dhl.com',
    'dhlparcel.pl',
    'dpd.com',
    'dpd.com.pl',
    'gls-group.com',
    'gls-poland.com',
    'fedex.com',
    'ups.com',
    'poczta-polska.pl',
    'orlenpaczka.pl',

    // Podróże / bilety / rezerwacje
    'booking.com',
    'airbnb.com',
    'ryanair.com',
    'lot.com',
    'wizzair.com',
    'skyscanner.net',
    'jakdojade.pl',
    'ebilet.pl',
    'eventim.pl',

    // Serwisy lokalne / ogłoszenia / usługi
    'otodom.pl',
    'olx.pl',
    'fixly.pl',
    'oferteo.pl',
    'gratka.pl',
    'pracuj.pl',
    'justjoin.it',
    'nofluffjobs.com',

    // Social / treści, gdzie skan zwykle ma mały sens lub psuje UX
    'youtube.com',
    'youtu.be',
    'netflix.com',
    'spotify.com',
    'twitch.tv',
    'pepper.pl',
    'github.com',
    'gitlab.com',

    // Hosting / code / docs / produktywność
    'notion.so',
    'notion.site',
    'figma.com',
    'miro.com',
    'atlassian.com',
    'jira.com',
    'confluence.com',
    'dropbox.com',
    'drive.google.com',
    'docs.google.com'
  ],
  sensitivityThreshold: 70,
  blockedPhrases: [],
  enableSpaMode: true,
  hideSlopCompletely: false,
  authorWhitelist: [],
  debugMode: false,
  enableTelemetry: false,
  remoteRulesUrl: '',
  activeModules: {
    posts: true,
    pages: false
  }
};